### ISSUE TITLE
TEST notification thread

### ISSUE THREAD

**Issue by maretree** [inf3rno/aurora-watch#12]
This is a thread where we can test the notifications

**Comment by inf3rno** [comment]
I got a notification.

**Comment by inf3rno** [comment]
Do you?

**Comment by maretree** [comment]
I did now that you have responded.

**Comment by inf3rno** [comment]
I'll create a test thread too. Let's see if you get notifications of new threads.

**Comment by maretree** [comment]
Yep just came in
